False True None
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/simulation_script.py", line 166, in run_simulation_and_get_balance
    model_results_df, expobj = run_simulation(args)
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/simulation_script.py", line 112, in run_simulation
    model_os.run_model(till_termination=True)
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/aquacrop/core.py", line 316, in run_model
    ) = self._perform_timestep()
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/aquacrop/core.py", line 379, in _perform_timestep
    new_cond, param_struct, outputs = solution_single_time_step_richards_hybrid(
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/aquacrop/timestep/run_single_timestep_richards_hybrid.py", line 257, in solution_single_time_step_richards_hybrid
    converged, new_th, _DeepPerc, _Runoff, _Infl, FluxOut = solverd.solve_daily(NewCond, Irr, Infl)
ValueError: too many values to unpack (expected 6)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/compute_water_balance.py", line 83, in <module>
    main()
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/compute_water_balance.py", line 79, in main
    compute_balance_process(hourly, use_richards, use_irrigation, texture)
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/compute_water_balance.py", line 40, in compute_balance_process
    for result in executor.map(run_simulation_and_get_balance, allargs):
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
ValueError: too many values to unpack (expected 6)
srun: error: node0217: task 0: Exited with exit code 1
